### ISSUE TITLE
Not able to authenticate

### ISSUE THREAD

**Issue by WesleyBatista** [jmagnusson/netsuite#1]
Hello,

I am trying to use the package _(which appears to be well done \o/ :beers: , but lacking some examples and documentation though :/)_. 

Unfortunately I am getting a `zeep.exceptions.Fault: Invalid login attempt.` exception.

I might be missing something. Could someone help me to figure out?

___

**code:**
```
import netsuite

ns = netsuite.NetSuite(**{
    'config': {
        'account': 'xxxxx',
        'consumer_key': 'xxxxxxxxxxxxxxxxxxxxxxxxxxx',
        'consumer_secret': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        'token_id': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        'token_secret': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    },
    'version': '2017.2.0',
})
print(ns.getList('employee', internalIds=[2222]))
```

**output:**
```
Traceback (most recent call last):
  File "netsuite_api2.py", line 13, in <module>
    print(ns.getList('employee', internalIds=[2222]))
  File "/home/wesley/.local/lib/python3.6/site-packages/netsuite/client.py", line 41, in wrapper
    response = fn(self, *args, **kw)
  File "/home/wesley/.local/lib/python3.6/site-packages/netsuite/client.py", line 436, in getList
    ) for externalId in externalIds
  File "/home/wesley/.local/lib/python3.6/site-packages/netsuite/client.py", line 407, in request
    return svc(*args, _soapheaders=self.generate_passport(), **kw)
  File "/home/wesley/.local/lib/python3.6/site-packages/zeep/proxy.py", line 42, in __call__
    self._op_name, args, kwargs)
  File "/home/wesley/.local/lib/python3.6/site-packages/zeep/wsdl/bindings/soap.py", line 132, in send
    return self.process_reply(client, operation_obj, response)
  File "/home/wesley/.local/lib/python3.6/site-packages/zeep/wsdl/bindings/soap.py", line 194, in process_reply
    return self.process_error(doc, operation)
  File "/home/wesley/.local/lib/python3.6/site-packages/zeep/wsdl/bindings/soap.py", line 299, in process_error
    detail=fault_node.find('detail'))
zeep.exceptions.Fault: Invalid login attempt.
```

**related python packages versions:**
>zeep==3.1.0
>netsuite==0.1.1

**Comment by WesleyBatista** [comment]
Once our account is Europe based and accessed from http://system.eu2.netsuite.com/ we wondered if the `wsdl_url` should be different to comply with the 'eu2' zone on the URL.

We managed to get a different error message by specifying the `wsdl_url` argument, `https://webservices.eu2.netsuite.com/wsdl/v2017_2_0/netsuite.wsdl`, like:
```python
ns = netsuite.NetSuite(**{
    'config': {
        'account': 'xxxxx',
        'consumer_key': 'xxxxxxxxxxxxxxxxxxxxxxxxxxx',
        'consumer_secret': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        'token_id': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        'token_secret': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    },
    'version': '2017.2.0',
    'wsdl_url': 'https://webservices.eu2.netsuite.com/wsdl/v2017_2_0/netsuite.wsdl',
})
```
The message now is: **`Fault: Invalid login. Customer access is disabled.`**

**Comment by WesleyBatista** [comment]
So, we were using these tutorials to learn how to interact with NetSuite:
 - https://rsmus.com/what-we-do/services/technology/erp-and-crm/netsuite/netsuite-tips-tricks/token-based-authentication-in-netsuite.html
 - http://cdn2.hubspot.net/hubfs/4259277/Techfino_March2018/Images/Token-Based-Authentication-Guide-for-NetSuite.pdf?t=1524742685505

The thing is that they assume that you already gave the "Web Services" permission to the role you are using, and don't mention about it on the posts.

Well, hope this help someone else :v:

**Comment by WesleyBatista** [comment]
For reference: http://kb.omni-ts.com/entry/1741/
