### ISSUE TITLE
Not able to make the getAll method work

### ISSUE THREAD

**Issue by ALB5** [jmagnusson/netsuite#10]
Hi,

I am trying to get all the Expense Report from Netsuite. I tested get and getList method with success. But I am not able to use the getAll method.

Here is my code: `client.getAll('expenseReport')`

And here the message I get:
```Traceback (most recent call last):
  File "main_netsuite.py", line 9, in <module>
    expensesReport = client.getAll('expenseReport')
  File "/home/alban/.virtualenvs/netsuite/lib/python3.7/site-packages/netsuite/client.py", line 50, in wrapper
    response = fn(self, *args, **kw)
  File "/home/alban/.virtualenvs/netsuite/lib/python3.7/site-packages/netsuite/client.py", line 525, in getAll
    recordType=recordType,
  File "/home/alban/.virtualenvs/netsuite/lib/python3.7/site-packages/netsuite/client.py", line 453, in request
    return svc(*args, _soapheaders=self.generate_passport(), **kw)
  File "/home/alban/.virtualenvs/netsuite/lib/python3.7/site-packages/zeep/proxy.py", line 45, in __call__
    kwargs,
  File "/home/alban/.virtualenvs/netsuite/lib/python3.7/site-packages/zeep/wsdl/bindings/soap.py", line 130, in send
    return self.process_reply(client, operation_obj, response)
  File "/home/alban/.virtualenvs/netsuite/lib/python3.7/site-packages/zeep/wsdl/bindings/soap.py", line 195, in process_reply
    return self.process_error(doc, operation)
  File "/home/alban/.virtualenvs/netsuite/lib/python3.7/site-packages/zeep/wsdl/bindings/soap.py", line 299, in process_error
    detail=fault_node.find("detail"),
zeep.exceptions.Fault: org.xml.sax.SAXException: expenseReport is not a legal value for {urn:types.core_2018_1.platform.webservices.netsuite.com}GetAllRecordType
```
I tested it with employee as well, it does not work either.

**Comment by jmagnusson** [comment]
Hi @ALB5,

Looks like expenseReport is not a legal value for the GetAllRecordType. I think that's the problem. You might have to use the search function instead.
