### ISSUE TITLE
Impossible to use with AWS Lambda because of a cache path issue

### ISSUE THREAD

**Issue by ALB5** [jmagnusson/netsuite#19]
When running this package on AWS Lambda we get this error:

```
[ERROR] OSError: [Errno 30] Read-only file system: '/home/sbx_user1051'
Traceback (most recent call last):
  File "/var/task/shared/config.py", line 207, in wrapper
    event=event, context=context, settings=settings, **kwargs
  File "/var/task/raven/contrib/awslambda/__init__.py", line 123, in wrapped
    return f(event, context, *args, **kwargs)
  File "/var/task/main.py", line 38, in lambda_handler
    event=event, context=context, settings=settings, force=False, dry_run=False
  File "/var/task/main.py", line 11, in main_handler
    expenses = extract_expense_data()
  File "/var/task/netsuite_api.py", line 48, in extract_expense_data
    raw_data = get_last_month_expenses()
  File "/var/task/netsuite_api.py", line 27, in get_last_month_expenses
    SearchStringField = client.Core.SearchStringField
  File "/var/task/netsuite/util.py", line 23, in __get__
    value = self.func(obj)
  File "/var/task/netsuite/client.py", line 255, in Core
    return self._type_factory('core', 'platform')
  File "/var/task/netsuite/client.py", line 249, in _type_factory
    return self.client.type_factory(
  File "/var/task/netsuite/util.py", line 23, in __get__
    value = self.func(obj)
  File "/var/task/netsuite/client.py", line 140, in client
    return self._generate_client()
  File "/var/task/netsuite/client.py", line 226, in _generate_client
    transport=self.transport,
  File "/var/task/netsuite/util.py", line 23, in __get__
    value = self.func(obj)
  File "/var/task/netsuite/client.py", line 144, in transport
    return self._generate_transport()
  File "/var/task/netsuite/client.py", line 190, in _generate_transport
    cache=self.cache,
  File "/var/task/netsuite/util.py", line 23, in __get__
    value = self.func(obj)
  File "/var/task/netsuite/client.py", line 132, in cache
    return self.__cache or self._generate_cache()
  File "/var/task/netsuite/client.py", line 182, in _generate_cache
    return SqliteCache(timeout=60 * 60 * 24 * 365)
  File "/var/task/zeep/cache.py", line 80, in __init__
    self._db_path = path if path else _get_default_cache_path()
  File "/var/task/zeep/cache.py", line 160, in _get_default_cache_path
    os.makedirs(path)
  File "/var/lang/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/var/lang/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/var/lang/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
```
Setting the path in the `client.py` module fixes the issue: 

```
def _generate_cache(self) -> zeep.cache.Base:
        return SqliteCache(timeout=60 * 60 * 24 * 365, path='/tmp/cache.db')
```

Could we allow the possibility to pass a custom path to the Netsuite class ?

**Comment by jmagnusson** [comment]
Hi @ALB5,

Submit a PR and I or @merit-sno will take a look at it.

**Comment by jmagnusson** [comment]
Just had a look at this. You can pass the `cache` argument to `netsuite.NetSuite` to override.
