### ISSUE TITLE
Bug in client.get using externalId

### ISSUE THREAD

**Issue by VeNoMouS** [jmagnusson/netsuite#25]
```
Traceback (most recent call last):
  File "./test.py", line 21, in <module>
    customer = client.get("customer", externalId=1000295) # 895 is the customer id
  File "/usr/local/lib/python3.7/dist-packages/netsuite/client.py", line 51, in wrapper
    response = fn(self, *args, **kw)
  File "/usr/local/lib/python3.7/dist-packages/netsuite/client.py", line 537, in get
    return self.request("get", baseRef=record_ref)
UnboundLocalError: local variable 'record_ref' referenced before assignment
```

```python
    @WebServiceCall(
        "body.readResponse", extract=lambda resp: resp["record"],
    )
    def get(
        self, recordType: str, *, internalId: int = None, externalId: str = None
    ) -> CompoundValue:
        """Get a single record"""
        if len([v for v in (internalId, externalId) if v is not None]) != 1:
            raise ValueError("Specify either `internalId` or `externalId`")

        if internalId:
            record_ref = self.Core.RecordRef(type=recordType, internalId=internalId,)
        else:
            self.Core.RecordRef(
                type=recordType, externalId=externalId,
            )

        return self.request("get", baseRef=record_ref)
```

The line 
```python
self.Core.RecordRef(
    type=recordType, externalId=externalId,
)
```
should read 
```python
record_ref = self.Core.RecordRef(
    type=recordType, externalId=externalId,
)
```

**Comment by jmagnusson** [comment]
Thanks @VeNoMouS. I've pushed a fix which should be available in v0.6.1
